<a href="https://colab.research.google.com/github/AndyHoskins87/PyTorch_DeepLearning/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__);

2.2.1+cu121


## Intro to Tensors



Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

* `Scalar` - single number 0 dimensions
* `Vector` - 1 dimension
* `Matrix` - 2 dimensional array of numbers
* `Tensor` - An n-dimensional array of numbers

In [ ]:
# Scalar 0 dimensions
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Vector 1 dimensions
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix 2 dimensions
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.shape, MATRIX.ndim

(torch.Size([2, 2]), 2)

In [ ]:
# Tensor n-dimensional array
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.shape, TENSOR.ndim

(torch.Size([1, 3, 3]), 3)

## Random Tensors



In [ ]:
# Create a random tensor of size (3, 4)
torch_rand = torch.rand(3, 4)
torch_rand

tensor([[0.7878, 0.1854, 0.8752, 0.8088],
        [0.9511, 0.7411, 0.5142, 0.0735],
        [0.3105, 0.5970, 0.4204, 0.7734]])

In [ ]:
torch_rand.shape, torch_rand.ndim

(torch.Size([3, 4]), 2)

In [ ]:
# Create a tensor based on an image
Image_rand = torch.rand(size=(3, 224, 224)) # colour channels, height, width
Image_rand.ndim, Image_rand.shape

(3, torch.Size([3, 224, 224]))

## Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensors

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data Types

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # defaults to None, which is torch.float32
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

When you run into issues in PyTorch, it's very often one to do with one of the three attributes above.

In [ ]:
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

## Manipulating Tensors (Tensor Operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise
* Divison
* Matrix Multiplication

In [ ]:
# Create a Tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Create a Tensor and multiply by 10
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# You can also use torch functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

## Matrix Multiplication

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul()  https://pytorch.org/docs/stable/generated/torch.matmul.html


* Element-wise multiplication	`[1*1, 2*2, 3*3]` = `[1, 4, 9]`	tensor * tensor
* Matrix multiplication	`[1*1 + 2*2 + 3*3]` = `[14]`	tensor.matmul(tensor)

In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.59 ms, sys: 1.1 ms, total: 2.68 ms
Wall time: 6.77 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 980 µs, sys: 59 µs, total: 1.04 ms
Wall time: 753 µs


tensor(14)